---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  'tag:RepositoryId': "{{ lookup('ansible.builtin.env', 'GITHUB_REPOSITORY_ID') }}"
  'tag:RunId': "{{ lookup('ansible.builtin.env', 'GITHUB_RUN_ID') }}"
  'tag:Environment': test
  'tag:Repository': "{{ lookup('ansible.builtin.env', 'GITHUB_REPOSITORY') }}"

hostnames:
  - instance-id

strict: true

groups:
  pdq_servers: 'true'

compose:
  ansible_host: public_ip_address
  ansible_connection: "'ssh'"
  ansible_user: "'Administrator'"
  ansible_shell_type: "'cmd'"
  ansible_ssh_private_key_file: "lookup('ansible.builtin.env', 'CI_PRIVATE_KEY')"
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=accept-new'"
  ec2_instance_id: instance_id
  ec2_platform: "platform | default('linux', true)"
  ec2_state: state
  ec2_placement: placement
  ec2_tags: tags
