# =========================================================================================== #
# File: '{{ role_path }}/tasks/present_windows.yml'
# --- [ Description ] ----------------------------------------------------------------------- #
#
# Ensures the Windows prerequisites owned by the PDQ Deploy application role.
#
# =========================================================================================== #
---
- name: 'CONFIGURE | Create the PDQ Background Service User'
  block:
    - name: 'CONFIGURE | Create the local PDQ service account'
      no_log: true
      ansible.windows.win_user:
        name: '{{ config.service_account.name }}'
        password: '{{ config.service_account.password }}'
        state: 'present'
        groups:
          - 'Administrators'
        groups_action: 'add'
        password_never_expires: true
        user_cannot_change_password: true
        update_password: 'on_create'

    - name: 'CONFIGURE | Grant Log-On-as-Service to the PDQ service account'
      ansible.windows.win_user_right:
        name: 'SeServiceLogonRight'
        users:
          - '.\{{ config.service_account.name }}'
        action: 'add'

- name: 'CONFIGURE | Create the PDQ Deploy App Share'
  vars:
    __share_drive__: '{{ config.data_disks.share.drive_letter }}'
    __repo_path__: '{{ __share_drive__ ~ ":\\" ~ config.repository.dir_name }}'
  block:
    - name: 'CONFIGURE | Create the App Share repository directory'
      ansible.windows.win_file:
        path: '{{ __repo_path__ }}'
        state: 'directory'

    - name: 'CONFIGURE | Grant Users read and execute on the App Share'
      ansible.windows.win_acl:
        path: '{{ __repo_path__ }}'
        user: 'BUILTIN\Users'
        rights: 'ReadAndExecute'
        type: 'allow'
        state: 'present'
        inherit: 'ContainerInherit, ObjectInherit'
        propagation: 'None'

    - name: 'CONFIGURE | Grant Administrators full control on the App Share'
      ansible.windows.win_acl:
        path: '{{ __repo_path__ }}'
        user: 'BUILTIN\Administrators'
        rights: 'FullControl'
        type: 'allow'
        state: 'present'
        inherit: 'ContainerInherit, ObjectInherit'
        propagation: 'None'

    - name: 'CONFIGURE | Grant SYSTEM full control on the App Share'
      ansible.windows.win_acl:
        path: '{{ __repo_path__ }}'
        user: 'NT AUTHORITY\SYSTEM'
        rights: 'FullControl'
        type: 'allow'
        state: 'present'
        inherit: 'ContainerInherit, ObjectInherit'
        propagation: 'None'

    - name: 'CONFIGURE | Publish the Administrators-only App Share'
      ansible.windows.win_share:
        name: '{{ config.repository.share_name }}'
        path: '{{ __repo_path__ }}'
        full: 'Administrators'
        rule_action: 'set'
        caching_mode: 'None'
